### ISSUE TITLE
feed generation for a large e-shop - 40,000 products - the feed is not generated

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#5]
Good day

I tried your solution on an eshop with about 40,000 products and the feed cannot be generated.

If you need, I can provide you with a sandbox version for testing.

It is necessary to generate data after 1000 products per period...

**Comment by seldimi** [comment]
Hello.
You can try generating the feed by real cron or wp-cli support which was added today

Have a look at:
https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/wiki/FAQ

**Comment by lukasprelovsky** [comment]
Good day,

it did not solve our problem.

What is the path to the cron launcher?

in docu faq: wp-content/plugins/webexpert-glami-xml-feed/cron.php

but in plugin \glami-feed-generator-pixel-for-woocommerce-main\ there is no cron.php

thx

**Comment by seldimi** [comment]
Hello. Please update to the latest version.
Path was fixed on FAQ, its 
wp-content/plugins/glami-feed-generator-pixel-for-woocommerce/cron.php

**Comment by lukasprelovsky** [comment]
Good day,

I tested the whole solution, but the problem persists.

The solution would be if I could define the number of products to be processed.

feed_products_per_page

the solution would be the possibility of generating a feed divided into processes of, for example, 20 products.

how many products are processed in one batch now?

from other plugins for XML processing, I tried a variant where the default was to process a batch of 1000 products, and the solution was to change the limit to a smaller number, for example 20 products in a batch.

Thanks
